name: rex_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.1+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.2.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.0.8
  modal_bottom_sheet: ^3.0.0
  dotted_line: ^3.2.2
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.4
  intl: ^0.18.0
  lottie: ^3.1.2
  share_plus: ^10.1.3
  either_dart: ^1.0.0
  network_info_plus: ^6.1.2
  permission_handler: ^11.3.1
  phone_numbers_parser: ^9.0.3
  screenshot: ^3.0.0
  shared_preferences: ^2.0.18
  month_picker_dialog: ^2.1.0
  pinput: ^5.0.0
  timeago: ^3.5.0
  sprintf: ^7.0.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  encrypt: ^5.0.3
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.0.3
  overlay_support: ^2.1.0
  path_provider: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  sqflite: ^2.4.1
  pusher_channels_flutter: ^2.4.0
  flutter_local_notifications: ^19.0.0
  appcheck: ^1.5.4+1
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  connectivity_plus: ^6.1.4
  internet_connection_checker_plus: ^2.7.2
  battery_plus: ^6.2.2

dependency_overrides:
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/lottiefiles/
    - assets/svg/
    - assets/json/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
