name: rex_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.3.0
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  hooks_riverpod: ^2.3.4
  either_dart: ^1.0.0
  package_info_plus: ^8.0.0
  http_parser: ^4.0.2
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  string_validator: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


